export enum VALID_ENV_KEYS {
  OPENAI_API_KEY = "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",
  ANTHROPIC_API_KEY = "ANTHROPIC_API_KEY",
  GOOGLE_GEMINI_API_KEY = "GOOGLE_GEMINI_API_KEY",
  MISTRAL_API_KEY = "MISTRAL_API_KEY",
  GROQ_API_KEY = "GROQ_API_KEY",
  PERPLEXITY_API_KEY = "PERPLEXITY_API_KEY",
  AZURE_OPENAI_API_KEY = "AZURE_OPENAI_API_KEY",
  OPENROUTER_API_KEY = "OPENROUTER_API_KEY",

  OPENAI_ORGANIZATION_ID = "proj_2jGjoviTulOtQDw07AezwJXI",

  AZURE_OPENAI_ENDPOINT = "AZURE_OPENAI_ENDPOINT",
  AZURE_GPT_35_TURBO_NAME = "AZURE_GPT_35_TURBO_NAME",
  AZURE_GPT_45_VISION_NAME = "AZURE_GPT_45_VISION_NAME",
  AZURE_GPT_45_TURBO_NAME = "AZURE_GPT_45_TURBO_NAME",
  AZURE_EMBEDDINGS_NAME = "AZURE_EMBEDDINGS_NAME",
}
